spring.application.name=EstudosDeJava

spring.application.name=EstudosDeJava

#= H2 (banco em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Console H2 (opcional - ver banco via browser)
spring.h2.console.enabled=true
